### ISSUE TITLE
[Community] Nominating Yuandong Xie (GithubID: xieydd) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#40]
Dear  Fluid TOC members and maintainers,

I am proposing to have Yuandong Xie (GithubID: xieydd) as a new committer. 

Yuandong Xie, is a senior engineer of Tencent Cloud. He works in Tencent Kubernetes Engine(TKE) team, focuses on cloud native AI infrastructure and other kubernetes related products. Yuandong also focus on elastic kubernetes service on tencent cloud. He likes to explore and contribute to open source technologies, is also member of kubeflow、Istio and fluid community.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=xieydd
Feb 26th, 2022

Contributed to the growth of community , expand the user case of fluid. Add new runtime of fluid – GooseFSRuntime, Provides fluid monitoring、stability enhancements and enterprise-level needs. 

Talks/Presentations/Blogs
====================
Talks:
KubeCon 2021 China: Fluid : Kubernetes 原生分布式数据集协调器和加速器
[https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/program/schedule/](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/program/schedule/)
KubeCon 2021 NorthAmerican: Fluid- Build Data Orchestration in Kubernetes. 
[https://sched.co/lV2U](https://sched.co/lV2U)
Fluid Community Meeting talks: Plan Discussion for BigData App Integration for Fluid
[https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20210630](https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20210630)
Blogs:
[https://cloud.tencent.com/developer/article/1868108](https://cloud.tencent.com/developer/article/1868108)

Major contributions
====================
v0.3.0:
Support the underlay storage which is configured only with non-root: [https://github.com/fluid-cloudnative/fluid/pull/168](https://github.com/fluid-cloudnative/fluid/pull/168)

v0.4.0:
Support deploying multiple dataset in the same node: [https://github.com/fluid-cloudnative/fluid/pull/242](https://github.com/fluid-cloudnative/fluid/pull/242)

v0.5.0:
Enhance Prometheus monitoring support for AlluxioRuntime: [https://github.com/fluid-cloudnative/fluid/pull/466](https://github.com/fluid-cloudnative/fluid/pull/466)

v0.6.0:
Enhance HA support for cache Runtime: [https://github.com/fluid-cloudnative/fluid/pull/781](https://github.com/fluid-cloudnative/fluid/pull/781)
Support new cache Runtime：GooseFS: [https://github.com/fluid-cloudnative/fluid/pull/912](https://github.com/fluid-cloudnative/fluid/pull/912)

Feel free to +1 or -1, starting with my +1.
Thanks,

Rong

**Comment by cheyang** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1, welcome

**Comment by TrafalgarZZZ** [comment]
+1
