### ISSUE TITLE
[Community] Nominating Tao Wang(GithubID: frankleaf) for Fluid committer 

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#41]
Dear Fluid TOC members and maintainers,

I am proposing to have Tao Wang(GithubID: frankleaf) as a new committer. 

Tao Wang, is a software engineer at Alibaba Cloud, works in the Open Source Big Data team, focusing on the combination of Fluid and JindoFS and also works on the development of Fluid and JindoFS core system, He is the core staff member of Fluid’s landing project on Alibaba inner scenarios and many AI and bigdata accelerating scene like weibo、zuoyebang etc.

The commit history: [https://github.com/fluid-cloudnative/fluid/commits?author=frankleaf](https://github.com/fluid-cloudnative/fluid/commits?author=frankleaf)

Talks/Presentations/Blogs
====================
Fluid Community Meeting talks: Introduction of Fluid JindoRuntime
（[https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20210923](https://www.infoq.cn/article/W65RcTI8AUhmoHVLkzWo?utm_source=tuicool&utm_medium=referral%20))）

Major contributions
====================
Fluid  v0.5.0:
Fluid Integrate With JindoRuntime Engine: [https://github.com/fluid-cloudnative/fluid/pull/493](https://github.com/fluid-cloudnative/fluid/pull/493)
Support JindoRuntime DataLoader: [https://github.com/fluid-cloudnative/fluid/pull/764](https://github.com/fluid-cloudnative/fluid/pull/764)

Fluid  v0.6.0:
Refactor Dataloader Code Structure To Engine Level: [https://github.com/fluid-cloudnative/fluid/pull/826](https://github.com/fluid-cloudnative/fluid/pull/826)

Fluid  v0.7.0:
Support QuotaList Regex With Multi DiskPath: [https://github.com/fluid-cloudnative/fluid/pull/678](https://github.com/fluid-cloudnative/fluid/pull/678)
JindoFuse Recover Automatically: [https://github.com/fluid-cloudnative/fluid/pull/1385](https://github.com/fluid-cloudnative/fluid/pull/1385)

Feel free to +1 or -1, starting with my +1.
Thanks,

Rong

**Comment by cheyang** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1
