### ISSUE TITLE
[Community] Nominating Weiwei Zhu(GithubID: zwwhdls) for Fluid committer 

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#44]
Dear Fluid TOC members and maintainers,

I am proposing to have Weiwei Zhu(GithubID: zwwhdls) as a new committer. 

Weiwei Zhu, is a software engineer at  Juicedata, Inc. She has made quite a lot of contribution to the Fluid open source project.

The commit history: [https://github.com/fluid-cloudnative/fluid/commits?author=zwwhdls](https://github.com/fluid-cloudnative/fluid/commits?author=zwwhdls)

Talks/Presentations/Blogs
====================
Fluid Community Meeting talks: Fluid Support Serverless Offline Task Lifecycle Management Design and Demonstration
(https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20220512)

Design Proposal for Fuse Recovery Feature
(https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20220120)

Blogs:
https://blog.hdls.me/16523685168321.html
https://juicefs.com/blog/cn/posts/fluid-with-juicefs

Major contributions
====================
v0.7.0:
Add JuiceFSRuntime engine to fluid backend:
https://github.com/fluid-cloudnative/fluid/pull/1047

mount point recover automatically
https://github.com/fluid-cloudnative/fluid/pull/1263

support juicefs in serverless
https://github.com/fluid-cloudnative/fluid/pull/1427

add feature gate to csi
https://github.com/fluid-cloudnative/fluid/pull/1444

0.8.0:
add fluid app controller
https://github.com/fluid-cloudnative/fluid/pull/1481

add app label in dataload & skip dataload pod inject
https://github.com/fluid-cloudnative/fluid/pull/1542

support juicefs cloud service
https://github.com/fluid-cloudnative/fluid/pull/1683

add label selector in controller cache
https://github.com/fluid-cloudnative/fluid/pull/1785

add code-gen in makefile
https://github.com/fluid-cloudnative/fluid/pull/1796

add configs in juicefsruntime
https://github.com/fluid-cloudnative/fluid/pull/1804

add eventDriven & cache selector in JuiceFSRuntime Controller
https://github.com/fluid-cloudnative/fluid/pull/1844

Feel free to +1 or -1, starting with my +1.
Thanks,

Rong

**Comment by cheyang** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1
