### ISSUE TITLE
[Community] Nominating Weiwei Zhu(GithubID: zwwhdls) for Fluid maintainer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#45]
Dear Fluid TOC members and maintainers,

I am proposing to have Weiwei Zhu(GithubID: zwwhdls) as a new maintainer.

Weiwei Zhu, is a fullstack engineer at Juicedata, maintainer of JuiceFS CSI Driver, focusing on the development of JuiceFS in cloud native scenarios and also works on combination of Fluid and JuiceFS.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=zwwhdls

Sep 16, 2022: Add ThinRuntime in order to make general storage easier to integrate Fluid.
Mar 31, 2022: Support JuiceFS Cloud Service edition in Fluid.
Mar 13, 2022: Add fluid app controller for serverless offline task lifecycle management.
Jan 1, 2022: Support Fluid fuse recovery feature. 
Nov 22, 2021: Add a new runtime for fluid - JuiceFSRuntime

## Talks/Presentations/Blogs

Talks:
KubeCon + CloudNativeCon Europe 2022 Office Hour
Fluid Community Meeting talks: Fluid Support Serverless Offline Task Lifecycle Management Design and Demonstration
(https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20220512)

Design Proposal for Fuse Recovery Feature
(https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20220120)

Blogs:
https://juicefs.com/zh-cn/blog/solutions/fluid-eci-juicefs
https://blog.hdls.me/16523685168321.html
https://juicefs.com/blog/cn/posts/fluid-with-juicefs

## Major contributions

v0.7.0:
Add JuiceFSRuntime engine to fluid backend: 
https://github.com/fluid-cloudnative/fluid/pull/1047

Mountpoint recover automatically: 
https://github.com/fluid-cloudnative/fluid/pull/1263

Support juicefs in serverless: 
https://github.com/fluid-cloudnative/fluid/pull/1427

Add feature gate to csi: 
https://github.com/fluid-cloudnative/fluid/pull/1444

0.8.0:
Add fluid app controller: 
https://github.com/fluid-cloudnative/fluid/pull/1481

Add app label in dataload & skip dataload pod inject: 
https://github.com/fluid-cloudnative/fluid/pull/1542

Support juicefs cloud service: 
https://github.com/fluid-cloudnative/fluid/pull/1683

Add label selector in controller cache: 
https://github.com/fluid-cloudnative/fluid/pull/1785

Add configs in juicefsruntime: 
https://github.com/fluid-cloudnative/fluid/pull/1804

Add eventDriven & cache selector in JuiceFSRuntime Controller: 
https://github.com/fluid-cloudnative/fluid/pull/1844

Support  tolerate in juicefsruntime: 
https://github.com/fluid-cloudnative/fluid/pull/2083

Add thinRuntime: 
https://github.com/fluid-cloudnative/fluid/pull/2098

Support emtpyDir for juicefs tiredstore volumeType: 
https://github.com/fluid-cloudnative/fluid/pull/2109

Add juicefs diagnose script and fix alluxio diagnose script: 
https://github.com/fluid-cloudnative/fluid/pull/2156

Add e2e test for juicefs: 
https://github.com/fluid-cloudnative/fluid/pull/2505

Feel free to +1 or -1, starting with my +1.
Thanks,

Rong

**Comment by cheyang** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
