### ISSUE TITLE
[Community] Nominating Lingwei Qiu(GithubID: yangyuliufeng) for Fluid maintainer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#46]
Dear Fluid TOC members and maintainers,

I am proposing to have Lingwei Qiu (GithubID: yangyuliufeng) as a new Fluid maintainer.

Lingwei Qiu, is a software engineer at China Telecom, works in the Paas R&D team, focusing on the planning and construction of container platforms and also works on the combination of Fluid and AI platforms. He is the core staff member of Fluid’s landing project in the China Telecom Cloud Native scene.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=yangyuliufeng

# Talks/Presentations/Blogs
Fluid Community Meeting talks: Plan Discussion for Fluid Operation Refactoring
（https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20221124）
Fluid Community Meeting talks: Plan Discussion for BigData App Integration for Fluid
（https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20211027）
Fluid Community Meeting talks: Optimize Pod scheduling through Fluid
（https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20210728）

# Major contributions
Fluid v0.4.0:
Split the Fluid controller into runtime controller and dataset controller: fluid-cloudnative/fluid#271
Refactor the start command and start function: fluid-cloudnative/fluid#232

Fluid v0.5.0:
Redesign the Cache runtime lifecycle and support backuping and restoring of Dataset: fluid-cloudnative/fluid#564, fluid-cloudnative/fluid#591

Fluid v0.6.0:
Cache-aware scheduling algorithm optimization: fluid-cloudnative/fluid#725
Dataset mount point dynamic update: fluid-cloudnative/fluid#954

Fluid v0.7.0:
Optimize CI process: fluid-cloudnative/fluid#1309, fluid-cloudnative/fluid#1368

help community members to design useful solutions for mount point automatically recovered

Fluid v0.8.0:
Redesign the startup logic of controller so that it can sense the change of certificate: fluid-cloudnative/fluid#1295,fluid-cloudnative/fluid#1420

Feel free to +1 or -1, starting with my +1.
Thanks,

Rong

**Comment by cheyang** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
