### ISSUE TITLE
[Community] Nominating Hao Ma (GithubID: allenhaozi) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#47]
Dear Fluid TOC members and maintainers,

I am proposing to have Hao Ma (GithubID: allenhaozi) as a new Fluid committer.

Hao Ma is a senior engineer for 4Paradigm. He works on the 4paradigm machine learning platform, Committed to the exploration, construction and implementation of MLOPS concept on the company's machine learning platform. He believes in open source, loves open source, willing to contribute to open source.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=allenhaozi

# Talks/Presentations/Blogs
Cache Runtime Support Container Network:     
(https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20220428) .       
build kubernetes csi development env by kind on Mac:     
(https://medium.com/@allenhaozi/build-kubernetes-csi-development-env-by-kind-on-mac-d61947b71661) .    
KubeMeet 杭州站开放报名，一起击破「云原生应用管理」痛点！      
(https://mp.weixin.qq.com/s/84VzBqrddi3LPSQuDrRnaQ) .     

# Major contributions

v0.8.2      
support image pull secrets [#2185](https://github.com/fluid-cloudnative/fluid/pull/2185)

v0.8.0    
Container Network with short-circuit read support [#1287](https://github.com/fluid-cloudnative/fluid/pull/1287)

v0.7.0     
unify the file format under cmd, alluxio jindo dataset [#1388](https://github.com/fluid-cloudnative/fluid/pull/1388)

v0.6.0      
add build fluid depvelopment env with kind on mac doc [#760](https://github.com/fluid-cloudnative/fluid/pull/760)

**Comment by cheyang** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
