### ISSUE TITLE
[Community] Nominating Shouzhuo Sun (GithubID: ssz1997) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#48]
Dear Fluid TOC members and maintainers,

I am proposing to have Shouzhuo Sun (GithubID: ssz1997) as a new committer.

Shouzhuo Sun is a software engineer of Alluxio. He works in Alluxio data team, focuses on cloud native applications, AI on Kubernetes, and other kubernetes related products. He is the point of contact from Alluxio for Alluxio runtime.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=ssz1997
Nov 5, 2021
Enable the fluid diagnose tool to obtain logs of Alluxio components. 
Feb 19, 2022
Mitigate Alluxio dataload slowness issue.

# Talks/Presentations/Blogs
Talks:
Fluid Community Meeting talks: Alluxio 2.9 new feature Sharing
https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20221222
Fluid Community Meeting talks: Recent Work on Alluxio Fuse
https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20220216

# Major contributions

v0.7.0:
Enable the fluid diagnose tool to obtain logs of Alluxio components: https://github.com/fluid-cloudnative/fluid/pull/1060
Mitigate Alluxio dataload slowness issue: https://github.com/fluid-cloudnative/fluid/pull/1450

v0.8.0:
Add Fluid with S3 documentation: https://github.com/fluid-cloudnative/fluid/pull/1494

Feel free to +1 or -1, starting with my +1.
Thanks,

Rong

**Comment by cheyang** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
