### ISSUE TITLE
[Community] Nominating Dongdong Lv (GithubID: ldd91) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#49]
Dear Fluid TOC members and maintainers,

I am proposing to have Dongdong Lv (GithubID: ldd91) as a new committer.

Dongdong Lv, Deep Learning Platform architect of Unisound,He is responsible for Unisound's large-scale distributed machine learning platform architecture design and new function evolution, deep learning algorithm application optimization and AI model acceleration. Research areas include large-scale cluster scheduling, high performance computing, distributed file storage, distributed cache, etc.  Participate in Fluid, Alluxio, JuiceFS, Volcano, Cube Studio and other open source projects.

As an early adopter of the Fluid, Actively participate in community weekly meetings and discussions, Contributed to the growth of community , expand the user case of fluid. cooperative development with JuiceData Team to add new runtime of fluid – JuicefsRuntime

### Talks/Presentations/Blogs ###

Talks:

 - 2022 Alluxio Day 11: [Speeding Up In Atlas Deep Learning Platform with Fluid+Alluxio](https://mp.weixin.qq.com/s/1g4OwwDnjj8G_mQ1hxES8A)

 - Fluid Community Meeting talks: [Add JuiceFSRuntime Engine To Fluid Backend](https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20211027)

Blogs:

 - [Speeding Up In Atlas Deep Learning Platform with Fluid+Alluxio](https://zhuanlan.zhihu.com/p/465288772)

 - [How to use Fluid + JuiceFS in the Kubernetes cluster](https://mp.weixin.qq.com/s?__biz=Mzg5MjUyNjExMw==&mid=2247486009&idx=1&sn=3b226a7701cc3b3c154cee2ee3dc3602&scene=21#wechat_redirect)
 - [Speeding Up the AI Supercomputing Platform - Practice at Unisound](https://dzone.com/articles/speeding-up-the-ai-supercomputing-platform-a-pract)

### Major contributions ###

v0.3.0:

 - Support the underlay storage which is configured only with non-root

v0.7.0:

 - Support New cache runtime: JuiceFS
 - Add juicefsruntime dataload function: https://github.com/fluid-cloudnative/fluid/pull/1539

**Comment by cheyang** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
