### ISSUE TITLE
[Community] Nominating Sichen Zhao (GithubID: hahchenchen) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#50]
Dear Fluid TOC members and maintainers,

I am proposing to have Sichen Zhao (GithubID: hahchenchen) as a new Fluid committer.

Sichen Zhao, is a software engineer at Shopee, works in the Paas team,focuses on cloud native AI infrastructure and other kubernetes related products, and also works on the combination of Fluid and AI platforms. He likes to explore and contribute to open source technologies, contributed to other communities like kubevela, Newlib, RTEMS, and fluid community.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=hahchenchen

Jan 8, 2023
Feature: Support sharedOptions in dataset
Dec 10, 2022
Optimization: set dataset mount.path of local/pvc , do no take effect. the
Dec 4, 2022
Optimization: when master worker delete, the dataset and runtime status do not changed
Dec 1, 2022
Feature: Support Fuse ds support onDelete updateStrategy for alluxioRuntime 
Nov 11, 2022
Optimization: Fix issue: 2294, set tieredstore in AlluxioRuntime do not affect memory request.
Nov 9, 2022
Optimization: Fix issue: 2198, when set alluxio runtime master port, do not take effect
Nov 7, 2022
Optimization: Fix the bug set Port Properties In alluxioRuntime, alluxio Pod crash
Sep 16, 2022
Optimization: Fix when alluxioruntime fuse args set, add mountPath in args 

# Talks/Presentations/Blogs

Blogs:
https://blog.csdn.net/hahachenchen789/article/details/128957437
https://blog.csdn.net/hahachenchen789/article/details/128957498
https://blog.csdn.net/hahachenchen789/article/details/128957585

# Major contributions

Fluid v0.8.3:
Support sharedOptions and sharedEncryptOptions  in dataset: [fluid-cloudnative/fluid#2574](https://github.com/fluid-cloudnative/fluid/pull/2574)

Fluid v0.8.2:
Support dataset use mount path of local/pv: .[fluid-cloudnative/fluid#2406](https://github.com/fluid-cloudnative/fluid/pull/2406)
Fix alluxio runtime bugs, set Port, set tieredstore, status changed when master/worker deleted: [fluid-cloudnative/fluid#2388](https://github.com/fluid-cloudnative/fluid/pull/2388), [fluid-cloudnative/fluid#2371](https://github.com/fluid-cloudnative/fluid/pull/2371), [fluid-cloudnative/fluid#2295](https://github.com/fluid-cloudnative/fluid/pull/2295), [fluid-cloudnative/fluid#2287](https://github.com/fluid-cloudnative/fluid/pull/2287)
Optimization for set Port Properties In alluxioRuntime : [fluid-cloudnative/fluid#2263](https://github.com/fluid-cloudnative/fluid/pull/2263)

Fluid v0.8.1:
Optimization for Alluxio runtime fuse args: [fluid-cloudnative/fluid#2135](https://github.com/fluid-cloudnative/fluid/pull/2135)

Feel free to +1 or -1, starting with my +1.
Thanks,

Rong

**Comment by cheyang** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
