### ISSUE TITLE
[Community] Nominating Ruofeng Lei (GithubID: abowloflrf) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#51]
Dear Fluid TOC members and maintainers,

I am proposing to have Ruofeng Lei (GithubID: abowloflrf) as a new committer.

Ruofeng Lei, is a senior software engineer of Baidu AI Cloud. He works in Baidu Cloud Container Engine (CCE) Team, focuses on cloud native AI infrastructure, helps users to develop, build and deploy AI applications on Kubernetes. He has a great contribution to Fluid's landing on Baidu AI Cloud and made it used in production. Besides Fluid, he also works on container GPU sharing and GPU scheduling, etc. 

The commit history: [https://github.com/fluid-cloudnative/fluid/commits?author=abowloflrf](https://github.com/fluid-cloudnative/fluid/commits?author=abowloflrf)  

# Major contributions

v0.7.0:  

Bug Fix: Fix update dataload status error
[fluid-cloudnative/fluid#1433](https://github.com/fluid-cloudnative/fluid/pull/1433)

v0.8.0

Bug Fix: Fix: runtime deletion issue
[fluid-cloudnative/fluid#1971](https://github.com/fluid-cloudnative/fluid/pull/1971)

Optimizations: Update dataset mountPoint min-length to 5
[fluid-cloudnative/fluid#2010](https://github.com/fluid-cloudnative/fluid/pull/2010)

Enhancement: Support leader election for controller and webhook
[fluid-cloudnative/fluid#2011](https://github.com/fluid-cloudnative/fluid/pull/2011)
[fluid-cloudnative/fluid#2014](https://github.com/fluid-cloudnative/fluid/pull/2014)

Enhancement: Update node `/etc/updatedb.conf` config in csi plugin
[fluid-cloudnative/fluid#2078](https://github.com/fluid-cloudnative/fluid/pull/2078)
[fluid-cloudnative/fluid#2075](https://github.com/fluid-cloudnative/fluid/pull/2075)

**Comment by cheyang** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
