### ISSUE TITLE
[Community] Nominating Zifan Ni (GithubID: zifanni) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#52]
Dear Fluid TOC members and maintainers,

I am proposing to have Zifan Ni (GithubID: zifanni) as a new Fluid committer.

Zifan Ni, was a software engineer at Bilibili, works in the AI platform team, focusing on the storage and its accelaration for AI platforms. He is the core member of Fluid’s landing project in the Bilibili AI platform scene.

The commit history:  [https://github.com/fluid-cloudnative/fluid/commits?author=nizifan](https://github.com/fluid-cloudnative/fluid/commits?author=nizifan)  

Jan 4, 2022  
[[BugFix] change mountTime to *v1.Time](https://github.com/fluid-cloudnative/fluid/commit/df23bdfe3f658d4ae1a8a595f0b0a17db03ed520)

Aug 6, 2021  
[disable fuse.shared.caching.reader.enabled for alluxio and goosefs, see Alluxio/alluxio#14909 (#1400)](https://github.com/fluid-cloudnative/fluid/commit/e2954bea954d0eecfe1d61bf8ea7d4cac3c1567f)

Jan 2, 2021  
[Add remount check for hostpath mount during sync](https://github.com/fluid-cloudnative/fluid/commit/f624578abad12231e8b7b67e9d23df442e39b1bb)

April 4, 2022  
[Fix bug in helm template](https://github.com/fluid-cloudnative/fluid/commit/1e05a43ba83972dbaccd272d0f184e3aa605f50a)

# Talks/Presentations/Blogs

[When AI Meets Alluxio at Bilibili | Building an Efficient AI Platform for Data Preprocessing and Model Training](https://www.alluxio.io/blog/when-ai-meets-alluxio-at-bilibili-building-an-efficient-ai-platform-for-data-preprocessing-and-model-training/)
[Building an Efficient AI Training Platform at bilibili with Alluxio - YouTube](https://www.youtube.com/watch?v=DsZYW_txTqA)

# Major contributions

Fluid v0.6.0:  
Add remount check for hostpath mount during sync [fluid-cloudnative/fluid#1340](https://github.com/fluid-cloudnative/fluid/pull/1340)

**Comment by cheyang** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
