### ISSUE TITLE
Apply for Fluid Community Committer

### ISSUE THREAD

**Issue by wushiming540** [fluid-cloudnative/community#58]
Dear Fluid TOC members and maintainers,
I applied to wushiming (GithubID: wushiming540) as a new committer.
Wu Shiming, senior engineer of Huawei's NAIE platform, is responsible for large-scale distributed machine learning platform architecture design and new feature evolution, deep learning algorithm application optimization, and AI model acceleration. Research areas include large-scale cluster scheduling, high-performance computing, distributed file storage, distributed cache, etc. Participate in open source projects such as Fluid, Alluxio, and Volcano.
As an in-depth user of Fluid, I actively participate in weekly community meetings and discussions, contributing to the growth of the community and expanding Fluid's user cases.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=wushiming540
Aug 16, 2023
docs: build fluid compnent

## Talks/Presentations/Blogs
https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20231019

**Comment by RongGu** [comment]
It is moved here: https://github.com/fluid-cloudnative/community/issues/60
