### ISSUE TITLE
[Community] Nominating Xiaozheng Zhang (GithubID: zhang-x-z) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#59]
Dear Fluid TOC members and maintainers,

I am proposing to have Xiaozheng Zhang (GithubID: zhang-x-z) as a new Fluid committer.

Xiaozheng Zhang, now is a master student in Nanjing University, focusing on distributed stream processing engine. He is working on acclerating states access in cloud-native stream processing system with distributed cache.

The commit history:  [Commits · fluid-cloudnative/fluid · GitHub](https://github.com/fluid-cloudnative/fluid/commits?author=zhang-x-z)

Part of his recent commits:

Mar 1, 2024

[fix mount point validation for vineyard runtime](https://github.com/fluid-cloudnative/fluid/commit/bbab38c92f40ba2344fb2851da9358bebfb0f6c6)

Jan 21, 2024

[Integrate Fluid with Kubeflow Pipline](https://github.com/fluid-cloudnative/fluid/commit/d98b4ca39d3342e7837ffbe902cbe8786ab0f0fb)

Jan 12, 2024

[Fix incorrect conversion between integer types](https://github.com/fluid-cloudnative/fluid/commit/5206a2b0e2494797725941035012c9c7ee767c0f)

Dec 25, 2023

[validate the env variable MOUNT_ROOT](https://github.com/fluid-cloudnative/fluid/commit/769f0b7f911ca3d465801920594a6c1e623a55fc)

# Talks/Presentations/Blogs

[How to use Fluid in Kubeflow Pipelines - YouTube](https://www.youtube.com/watch?v=EZrzGEUcLp4)

# Major contributions

Bug Fix:

[Fix alluxio dataload bug](https://github.com/fluid-cloudnative/fluid/commit/e68ae2e43e59a30995e80887177ba815aee10199)

Optimization:

[fix mount point validation for vineyard runtime](https://github.com/fluid-cloudnative/fluid/commit/bbab38c92f40ba2344fb2851da9358bebfb0f6c6)

[Fix incorrect conversion between integer types](https://github.com/fluid-cloudnative/fluid/commit/5206a2b0e2494797725941035012c9c7ee767c0f)

Feature:  

[Integrate Fluid with Kubeflow Pipline](https://github.com/fluid-cloudnative/fluid/commit/d98b4ca39d3342e7837ffbe902cbe8786ab0f0fb)

Security:

[OS Command Injection for Fluid Users with JuicefsRuntime · Advisory · fluid-cloudnative/fluid](https://github.com/fluid-cloudnative/fluid/security/advisories/GHSA-wx8q-4gm9-rj2g)

Fluid 0.9.0:

[Adapt to libfuse 3](https://github.com/fluid-cloudnative/fluid/commit/66d64fdef88a1aa18f34461b021d2cfa94083215)

**Comment by cheyang** [comment]
+1

**Comment by RongGu** [comment]
+1

**Comment by yangyuliufeng** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
