### ISSUE TITLE
[Community] Nominating Wenxiao Wang (GithubID: wang-mask) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#61]
Dear Fluid TOC members and maintainers,

I am proposing to have Wenxiao Wang (GithubID: wang-mask) as a new committer.

Wenxiao Wang, a postgraduate student at Nanjing University, engages in Cloud Native research work in LANDS Laboratory. He focuses on extending Fluid to the field of table queries and actively contributes to the formulation of the datatable abstraction and its corresponding controllers, realizing the automation of table mounting and scaling.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=wang-mask

Mar 13, 2024    
[Fluid DataTable: cloud native table abstraction and controller in the realm of table queries](https://github.com/fluid-cloudnative/fluid/pull/3405)

Jan 21, 2024    
[Integrate fluid with kubeflow pipline](https://github.com/fluid-cloudnative/fluid/pull/3694)

Mar 4, 2023     
[Aadapt NFS to fluid thinruntime](https://github.com/fluid-cloudnative/fluid/pull/2687)

Nov 22, 2022     
[Support alluxioruntime.worker.nodeSelect function](https://github.com/fluid-cloudnative/fluid/pull/2336)

Oct 28, 2022    
[Update fluid dataset accessmode](https://github.com/fluid-cloudnative/fluid/pull/2224)

...

# Talks/Presentations/Blogs
Fluid Community Meeting talks: Take Presto as an example to introduce Fluid DataTable   
(https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20230316)

# Major contributions
Fluid Datatable:  
Datatable    
[fluid-cloudnative/fluid#2671](https://github.com/fluid-cloudnative/fluid/pull/2671)  

Fluid v0.9.0:  
update:update the accessmode   
[fluid-cloudnative/fluid#2224](https://github.com/fluid-cloudnative/fluid/pull/2224)  
update: translate the juicefs-setup.md to en & indicate we have supply the offical mul-platforms images  
[fluid-cloudnative/fluid#2154](https://github.com/fluid-cloudnative/fluid/pull/2154)   
feature: 2298 alluxioruntime support worker.nodeSelect      
[fluid-cloudnative/fluid#2336](https://github.com/fluid-cloudnative/fluid/pull/2336)   
testcase: add testcase 12    
[fluid-cloudnative/fluid#2429](https://github.com/fluid-cloudnative/fluid/pull/2429 )

Fluid v0.8.1:  
feature:add the toleration to fuse  
[fluid-cloudnative/fluid#2158](https://github.com/fluid-cloudnative/fluid/pull/2168)

Feel free to +1 or -1, starting with my +1.     
Thanks,

Rong

**Comment by cheyang** [comment]
+1

**Comment by RongGu** [comment]
+1

**Comment by yangyuliufeng** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
