### ISSUE TITLE
[Community] Nominating Zhiqiang Liu (GithubID: xliuqq) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#62]
Dear Fluid TOC members and maintainers,

I am proposing to have Zhiqiang Liu (GithubID: xliuqq) as a new committer.

Zhiqiang Liu, is a software engineer. He currently is engaged in work related to bigdata and cloud computing,  including large-scale cluster scheduling, high performance computing, distributed file system etc. He is interested in data access acceleration and cloud scheduling，and is willing to contribute in related open-source projects.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=xliuqq

# Talks/Presentations/Blogs

[Proposal: The affinity between Data Operation Pods in DataFlow](https://github.com/fluid-cloudnative/community/blob/master/proposals/dataoperation/v1.0_dataflow_affinity/v1.0_dataflow_affinity_en.md)

# Major contributions

**v0.9.0:**
Support for accessing data across namespaces: [fluid-cloudnative/fluid#2296](https://github.com/fluid-cloudnative/fluid/pull/2296),  [fluid-cloudnative/fluid#2358](https://github.com/fluid-cloudnative/fluid/pull/2358)

Support mount dataset with subpath: [fluid-cloudnative/fluid#2410](https://github.com/fluid-cloudnative/fluid/pull/2410)

Add random port allocator for runtime: [fluid-cloudnative/fluid#2057](https://github.com/fluid-cloudnative/fluid/pull/2057)

Use data operation framework to construct data migrate, load, backup behaviors: [fluid-cloudnative/fluid#2598](https://github.com/fluid-cloudnative/fluid/pull/2598), [fluid-cloudnative/fluid#2637](https://github.com/fluid-cloudnative/fluid/pull/2637), [fluid-cloudnative/fluid#2712](https://github.com/fluid-cloudnative/fluid/pull/2712), [fluid-cloudnative/fluid#2813](https://github.com/fluid-cloudnative/fluid/pull/2813), [fluid-cloudnative/fluid#3173](https://github.com/fluid-cloudnative/fluid/pull/3173)

**v1.0.0:**

Bugfix: fix Alluxio master in HA mode start error: [fluid-cloudnative/fluid#3658](https://github.com/fluid-cloudnative/fluid/pull/3658)

Bugfix: pass AccessModes to thinruntime fuse container: [fluid-cloudnative/fluid#3696](https://github.com/fluid-cloudnative/fluid/pull/3696)

Remove kubectl for runtime and dataset controller: [fluid-cloudnative/fluid#3716](https://github.com/fluid-cloudnative/fluid/pull/3716)

Support cron dataload: [fluid-cloudnative/fluid#3309](https://github.com/fluid-cloudnative/fluid/pull/3309)

Support ssh password free pod for parallel data migrate: [fluid-cloudnative/fluid#3645](https://github.com/fluid-cloudnative/fluid/pull/3645), [fluid-cloudnative/fluid#3732](https://github.com/fluid-cloudnative/fluid/pull/3732)

Support tiered locality scheduling for app pod : [fluid-cloudnative/fluid#3461](https://github.com/fluid-cloudnative/fluid/pull/3461)

Support webhook mutating plugins configurable: [fluid-cloudnative#3545](https://github.com/fluid-cloudnative/fluid/pull/3545)

**Comment by cheyang** [comment]
+1

**Comment by RongGu** [comment]
+1

**Comment by zwwhdls** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
