### ISSUE TITLE
[Community] Nominating Jun Yang (GithubID: yangjun289519474) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#63]
Dear Fluid TOC members and maintainers,

I am proposing to have Jun Yang (GithubID: yangjun289519474) as a new committer.

Jun Yang, is a software development engineer at Alibaba Cloud, works in the file system storage R&D team, focusing on the design and development of distributed file systems, as well as the construction of related cloud-native technology ecosystems. He is the core staff member of Fluid’s landing project of file system service, which called 'EFC' in the Alibaba Cloud.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=yangjun289519474
May 12, 2023
fix(efcruntime): add prefix efc to /dev/shm volume when eci (#3229)

May 9, 2023
fix(efcruntime): set Privileged=true when init-fuse start (#3221)

May 8, 2023
fix(efcruntime): remove init container and sessmgr in efc-master yaml (#3216)

May 6, 2023
efcruntime remove unreasonable config to support eci features (#3206)

May 4, 2023
Refactor efc images (#3200)

Apr 20, 2023
Refactor eacruntime yaml to efcruntime yaml (#3123)

Apr 19, 2023
remane eac engine to efc engine (#3074)

Apr 14, 2023
Refactor eacruntime to efcruntime (#3046)

Apr 13, 2023
Refactor eac crd: reaname eac to efc (#3023)

Feb 16, 2023
add fuse-master image, and update eacruntime version (#2604)

Feb 15, 2023
fix eac-fuse mount options (#2595)

# Talks/Presentations/Blogs
Fluid Community Meeting talks: An Introduction to Fluid EFCRuntime
（https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20230525）

# Major contributions
Fluid v0.9.0:
Remove init container and sessmgr in efc-master yaml: fluid-cloudnative/fluid#3216
Refactor efc runtime controller: fluid-cloudnative/fluid#3046

Feel free to +1 or -1, starting with my +1.
Thanks,

Rong

**Comment by cheyang** [comment]
+1

**Comment by RongGu** [comment]
+1

**Comment by yangyuliufeng** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
