### ISSUE TITLE
[Community] Nominating Ye Cao (GithubID: dashanji)  for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#64]
Dear Fluid TOC members and maintainers,

I am proposing to have Ye Cao (GithubID: dashanji) as a new Fluid committer.

Ye Cao, is a software engineer at Alibaba, works in the TongYi team, focusing on distributed storage, cloud computing and AI platforms. He is maintainer of Vineyard, a
distributed in-memory data manager. He likes open source and is also a PMC member of Apache Skywalking.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=dashanji
May 27, 2024
Support to configure the cache size of vineyard fuse.
Apr 9, 2024
Add the tutorial about how to use Vineyard runtime to accelerate the kubeflow pipelines.
Apr 4, 2024
Add the doc about how to use Vineyard runtime.
Jan 9, 2024
Implement Vineyard runtime engine and controller.
Dec 27, 2023
Add the controller and rbac yaml for Vineyard runtime.
Dec 22, 2023
Add the helm chart for Vineyard runtime.
Nov 24, 2023
Add the Vineyard runtime CRD definitions.
Nov 9, 2023
Introduce the Vineyard runtime to Fluid.

Talks/Presentations/Blogs
KCD Shanghai 2024: 助力大模型生产, Fluid与Vineyard携手打造kubernetes中的高效中间数据管理
Fluid Community Meeting talks: Use vineyard to accelerate kubeflow pipelines in the fluid platform
（https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20240118）
Fluid Community Meeting talks: Vineyard Runtime Design
（https://github.com/fluid-cloudnative/community/wiki/Meeting-Agenda-and-Notes#20231109）

Major contributions
Fluid v1.0.0:
Implemented A new runtime for sharing in-memory immutable data: VineyardRuntime is supported in Fluid.
https://github.com/fluid-cloudnative/fluid/issues/3528
https://github.com/fluid-cloudnative/fluid/pull/3555
https://github.com/fluid-cloudnative/fluid/pull/3624
https://github.com/fluid-cloudnative/fluid/pull/3659
https://github.com/fluid-cloudnative/fluid/pull/3649
https://github.com/fluid-cloudnative/fluid/pull/3982

Feel free to +1 or -1, starting with my +1.
Thanks,

Rong

**Comment by cheyang** [comment]
+1

**Comment by RongGu** [comment]
+1

**Comment by zwwhdls** [comment]
+1

**Comment by yangyuliufeng** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
