### ISSUE TITLE
[Community] Nominating Shunli Feng (GithubID: fengshunli) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#65]
Dear Fluid TOC members and maintainers,

I am proposing to have Shunli Feng (GithubID: fengshunli) as a new committer.

Shunli Feng, is a partner of a startup company. He has worked in cloud-native container security for many years and has extensive experience in container security and cloud-native technologies. He is also a contributor and maintainer of multiple security projects and cloud-native technologies.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=fengshunli
Apr 5, 2023

Major contributions
v0.9.3 v0.9.2 v0.9.1 v0.9.0:
Add specify namespace installation: fluid-cloudnative/fluid#2700
Remove deprecated serviceAccount: fluid-cloudnative/fluid#2705

v1.0.0:
Update alpine 3.17 to 3.18: fluid-cloudnative/fluid#3254
Add OpenSSF Scorecard for README.md: fluid-cloudnative/fluid#2685
Add specify namespace installation: fluid-cloudnative/fluid#2700

Feel free to +1 or -1, starting with my +1.
Thanks,

**Comment by cheyang** [comment]
+1

**Comment by RongGu** [comment]
+1

**Comment by yangyuliufeng** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
