### ISSUE TITLE
[Community] Nominating Ni Wang (GithubID: uniqueni) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#66]
Dear Fluid TOC members and maintainers,

I am proposing to have Ni Wang (GithubID: uniqueni) as a new Fluid committer.

Ni Wang formerly worked at 4Paradigm, focusing on integrating Fluid with Alluxio on the AI platform during their tenure. Currently, she is working in the Beike container team, focus on fluid landing in large model training and reasoning scenarios

 The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=uniqueni 
 Jan 25, 2024
 Add enableServiceLinks to EFC and JuiceFS 
 Feb 11, 2023
 Add Istio sidecar annotations to Fluid runtime components
 Feb 10, 2023
 Fix bug [#2521](https://github.com/fluid-cloudnative/fluid/issues/2521),allowing Alluxio runtime master and worker properties to be overridden
 Dec 20, 2021
 Discover and fix the bug[#1293](https://github.com/fluid-cloudnative/fluid/issues/1293)
 Nov 17, 2021
 Support resource configuration for Alluxio runtime job master and worker

 # Major contributions
Fluid v0.7.0:
Fix setting resources to jobmaster and jobworker [fluid-cloudnative/fluid#1125](https://github.com/fluid-cloudnative/fluid/pull/1125)

Fluid v0.9.0:
[FEATURES] Add sidecar.istio.io/inject: "false" to runtime components[fluid-cloudnative/fluid#2531](https://github.com/fluid-cloudnative/fluid/issues/2531)
fix bug Failed to override Alluxio's properties in spec.master or spec.worker[fluid-cloudnative/fluid#2521](https://github.com/fluid-cloudnative/fluid/issues/2521)

Fluid v1.0.0
Features for enable servicelinks to all runtime[fluid-cloudnative/fluid#3730](https://github.com/fluid-cloudnative/fluid/pull/3703)

**Comment by cheyang** [comment]
+1

**Comment by RongGu** [comment]
+1

**Comment by yangyuliufeng** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
