### ISSUE TITLE
[Community] Nominating Weixiao Huang (GithubID: weixiao-huang) for Fluid committer

### ISSUE THREAD

**Issue by RongGu** [fluid-cloudnative/community#67]
Dear Fluid TOC members and maintainers,

I am proposing to have Weixiao Huang (GithubID: weixiao-huang) as a new committer.

Weixiao Huang, senior engineer of Megvii Technology. As an developer and in-depth user of Fluid, he actively participates in weekly community meetings and discussions, contributing to the growth of the community and expanding Fluid's user cases.

The commit history: https://github.com/fluid-cloudnative/fluid/commits?author=weixiao-huang

Best,
Rong

**Comment by cheyang** [comment]
+1

**Comment by RongGu** [comment]
+1

**Comment by yangyuliufeng** [comment]
+1

**Comment by TrafalgarZZZ** [comment]
+1

**Comment by wsxiaozhang** [comment]
+1
